version: "3.11"

services:
  flask-app:
    image: harryphoebus/ml_assignment03:latest
    platform: linux/amd64  # Ensure correct platform
    container_name: oaksoekyaw_ml_assignment03
    # ports:
    #   - "5001:5001"
    # restart: always
    environment:
      - Host=0.0.0.0
      - Port=5001

    labels:
      # Enable Traefik reverse proxy
      - "traefik.enable=true"
      # Define backend service port for Traefik
      - "traefik.http.services.web-st125064_03.loadbalancer.server.port=5001"
      # Define routing for development
      - "traefik.http.routers.web-st125064_03.rule=Host(`st125064_03.ml.brain.cs.ait.ac.th`)"
      # Enable SSL for testing (optional)
      - "traefik.http.routers.web-st125064_03.tls=true"
      - "traefik.http.routers.web-st125064_03.tls.certresolver=staging"
      - "traefik.http.routers.web-st125064_03.entrypoints=websecure"

    networks:
      - default
      - traefik_default

networks:
  default:
  traefik_default:
    external: true



